size:
  x: 1000
  z: 1000


team-size: 2
world-type: NORMAL
environment: NORMAL
world-seed:
generate-structures: true
world-name: "UHCWorld"
friendly-fire-protection-seconds: 30
pregame-phase-seconds: 300
main-phase-seconds: 1800
endgame-phase-seconds: 300
<<<<<<< HEAD
starter-kit:
  inventory: []
  helmet:
  chestplate:
  leggings:
  boots:

goal-schematic: 'goals/beacon.schematic'
=======
starter-kit: []
>>>>>>> 5f7024c56dd7ddfe593bda99c7818e6f76b41490
