name: ${project.name}
version: ${project.version}
main: ${project.main}
authors: ${project.authors}

commands:
  uhc:
    usage: /uhc [start|end]
    permission: uhc.commands.uhc

  team:
    usage: /team <teamname>
    permission: uhc.commands.team
    description: create a team

  scratch:
    usage: /scratch
    permission: uhc.staff

permissions:
  uhc.commands.team:
    default: true
  uhc.commands.team.join:
    default: true
  uhc.commands.team.invite:
    default: true
  uhc.commands.team.leave:
    default: true
  uhc.commands.team.create:
    default: true
